import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { optimize } from 'svgo'
import { createDb, listIcons, type Icon } from '@web-portfolio/icons-db'
import type { GeneratedEntry, GeneratedRegistry, Metadata, Registry } from '../src/types'

// Icons stored from a "plain"/"line" devicon variant are monochrome glyphs
// meant to be recolored; "original"/"original-wordmark" variants are
// multi-color brand marks whose colors should be left alone. "material",
// "social", and "tools" (Material Symbols, Simple Icons) are monochrome by
// design too — this is a no-op for them today since their source SVGs have
// no inner fill attributes to rewrite in the first place (they inherit
// color instead), but keeps the categorization semantically correct if that
// ever changes.
const MONOCHROME_CATEGORIES = new Set(['plain', 'line', 'material', 'social', 'tools'])

export function splitSvg(svg: string): { viewBox: string; innerHTML: string } {
  const openTagMatch = svg.match(/<svg\b([^>]*?)(\/)?>/i)
  if (!openTagMatch) {
    throw new Error('Invalid SVG: missing <svg> root element')
  }
  const [openTag, attrs, selfClosing] = openTagMatch
  const viewBoxMatch = attrs.match(/viewBox="([^"]*)"/i)
  const viewBox = viewBoxMatch?.[1] ?? '0 0 24 24'

  if (selfClosing) {
    return { viewBox, innerHTML: '' }
  }

  const closeIndex = svg.lastIndexOf('</svg>')
  if (closeIndex === -1) {
    throw new Error('Invalid SVG: missing closing </svg> tag')
  }

  return {
    viewBox,
    innerHTML: svg.slice(openTagMatch.index! + openTag.length, closeIndex).trim(),
  }
}

export function normalizeToCurrentColor(innerHTML: string): string {
  return innerHTML
    .replace(/(\sfill=")(?!none")[^"]*(")/gi, '$1currentColor$2')
    .replace(/(\sstroke=")(?!none")[^"]*(")/gi, '$1currentColor$2')
}

type IconLike = Pick<Icon, 'svg' | 'label' | 'tags' | 'category'>

export function buildRegistryEntry(icon: IconLike): GeneratedEntry {
  const optimized = optimize(icon.svg, {
    multipass: true,
    plugins: [{ name: 'preset-default', params: { overrides: { removeViewBox: false } } }],
  })

  const { viewBox, innerHTML } = splitSvg(optimized.data)
  const isMonochrome = icon.category ? MONOCHROME_CATEGORIES.has(icon.category) : false

  return {
    viewBox,
    innerHTML: isMonochrome ? normalizeToCurrentColor(innerHTML) : innerHTML,
    label: icon.label,
    tags: JSON.parse(icon.tags) as string[],
    category: icon.category,
  }
}

export function buildRegistry(rows: (IconLike & { name: string })[]): GeneratedRegistry {
  const registry: GeneratedRegistry = {}
  for (const row of rows) {
    registry[row.name] = buildRegistryEntry(row)
  }
  return registry
}

/**
 * `@web-portfolio/icons` only ever reads `viewBox`/`innerHTML`;
 * `@web-portfolio/icons-sanity`'s picker only ever reads
 * `label`/`tags`/`category` for search and delegates actual rendering to
 * `@web-portfolio/icons`. Splitting here means each package's build only
 * inlines the half of the data it uses, instead of both packages shipping
 * every field for every icon.
 */
export function splitEntries(full: GeneratedRegistry): { registry: Registry; metadata: Metadata } {
  const registry: Registry = {}
  const metadata: Metadata = {}
  for (const [name, entry] of Object.entries(full)) {
    registry[name] = { viewBox: entry.viewBox, innerHTML: entry.innerHTML }
    metadata[name] = { label: entry.label, tags: entry.tags, category: entry.category }
  }
  return { registry, metadata }
}

function serializeRegistry(registry: Registry): string {
  return [
    '// Generated by scripts/generate-registry.ts — do not edit by hand.',
    "// Run `pnpm generate-registry` from the repo root to regenerate.",
    "import type { Registry } from './types'",
    '',
    `export const registry: Registry = ${JSON.stringify(registry, null, 2)}`,
    '',
  ].join('\n')
}

function serializeMetadata(metadata: Metadata): string {
  return [
    '// Generated by scripts/generate-registry.ts — do not edit by hand.',
    "// Run `pnpm generate-registry` from the repo root to regenerate.",
    "import type { Metadata } from './types'",
    '',
    `export const metadata: Metadata = ${JSON.stringify(metadata, null, 2)}`,
    '',
  ].join('\n')
}

// createDb's local-file fallback (`file:./local.db`) is resolved against the
// current working directory. Every seed script runs from packages/db, but this
// one runs from packages/core — so without an explicit path the two read two
// different files, and this one silently finds an empty database. Turso env
// vars, when set, still take precedence.
const LOCAL_DB_URL = `file:${path.resolve(import.meta.dirname, '../../db/local.db')}`

async function main() {
  const db = createDb(process.env.TURSO_DATABASE_URL ? {} : { url: LOCAL_DB_URL })
  const rows = await listIcons(db)
  const full = buildRegistry(rows)
  const { registry, metadata } = splitEntries(full)
  writeFileSync(path.join(import.meta.dirname, '../src/registry.generated.ts'), serializeRegistry(registry))
  writeFileSync(path.join(import.meta.dirname, '../src/metadata.generated.ts'), serializeMetadata(metadata))
  console.log(
    `Wrote ${Object.keys(registry).length} icons to registry.generated.ts and metadata.generated.ts`,
  )
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
