// Generated by scripts/generate-registry.ts — do not edit by hand.
// Run `pnpm generate-registry` from the repo root to regenerate.
import type { Metadata } from './types'

export const metadata: Metadata = {
  "aarch64": {
    "label": "Aarch64",
    "tags": [
      "architecture",
      "programming",
      "language",
      "ARM",
      "arm64"
    ],
    "category": "plain"
  },
  "add": {
    "label": "Add",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "adonisjs": {
    "label": "Adonisjs",
    "tags": [
      "nodejs",
      "framework",
      "adonis"
    ],
    "category": "original"
  },
  "aerospike": {
    "label": "Aerospike",
    "tags": [
      "data",
      "database",
      "nosql"
    ],
    "category": "original"
  },
  "aframe": {
    "label": "Aframe",
    "tags": [
      "framework",
      "html",
      "javascript",
      "js",
      "web",
      "a-frame"
    ],
    "category": "plain"
  },
  "aftereffects": {
    "label": "Aftereffects",
    "tags": [
      "video",
      "editor",
      "adobeaftereffects",
      "ae"
    ],
    "category": "plain"
  },
  "akka": {
    "label": "Akka",
    "tags": [
      "framework",
      "java",
      "scala",
      "open-source",
      "akka-framework"
    ],
    "category": "original"
  },
  "algolia": {
    "label": "Algolia",
    "tags": [
      "algorithms",
      "api",
      "documentation",
      "tool"
    ],
    "category": "original"
  },
  "almalinux": {
    "label": "Almalinux",
    "tags": [
      "linux",
      "os",
      "open-source",
      "AlmaLinux OS"
    ],
    "category": "plain"
  },
  "alpinejs": {
    "label": "Alpinejs",
    "tags": [
      "framework",
      "javascript",
      "Alpine"
    ],
    "category": "original"
  },
  "alternate_email": {
    "label": "Email",
    "tags": [
      "communication",
      "email",
      "contact",
      "at"
    ],
    "category": "material"
  },
  "amazonwebservices": {
    "label": "Amazonwebservices",
    "tags": [
      "cloud",
      "hosting",
      "server",
      "aws"
    ],
    "category": "original-wordmark"
  },
  "anaconda": {
    "label": "Anaconda",
    "tags": [
      "python",
      "data-science"
    ],
    "category": "original"
  },
  "android": {
    "label": "Android",
    "tags": [
      "os",
      "mobile"
    ],
    "category": "plain"
  },
  "androidstudio": {
    "label": "Androidstudio",
    "tags": [
      "application",
      "editor",
      "jetbrains",
      "ide",
      "android",
      "mobile"
    ],
    "category": "plain"
  },
  "angular": {
    "label": "Angular",
    "tags": [
      "framework",
      "javascript"
    ],
    "category": "plain"
  },
  "angularjs": {
    "label": "Angularjs",
    "tags": [
      "framework",
      "javascript"
    ],
    "category": "plain"
  },
  "angularmaterial": {
    "label": "Angularmaterial",
    "tags": [
      "framework",
      "javascript"
    ],
    "category": "plain"
  },
  "ansible": {
    "label": "Ansible",
    "tags": [
      "automation",
      "provisioning",
      "deployment",
      "continuous-delivery"
    ],
    "category": "plain"
  },
  "ansys": {
    "label": "Ansys",
    "tags": [
      "simulation"
    ],
    "category": "plain"
  },
  "antdesign": {
    "label": "Antdesign",
    "tags": [
      "reactjs",
      "design",
      "language"
    ],
    "category": "plain"
  },
  "apache": {
    "label": "Apache",
    "tags": [
      "php",
      "The Apache Software Foundation"
    ],
    "category": "plain"
  },
  "apacheairflow": {
    "label": "Apacheairflow",
    "tags": [
      "platform",
      "pipeline",
      "orchestrator",
      "open-source",
      "Airflow"
    ],
    "category": "plain"
  },
  "apachekafka": {
    "label": "Apachekafka",
    "tags": [
      "streaming",
      "open-source"
    ],
    "category": "original"
  },
  "apachespark": {
    "label": "Apachespark",
    "tags": [
      "data-processing",
      "data-science",
      "machine-learning"
    ],
    "category": "original"
  },
  "apex": {
    "label": "Apex",
    "tags": [
      "language"
    ],
    "category": "original"
  },
  "apl": {
    "label": "Apl",
    "tags": [
      "programming",
      "language",
      "open-source",
      "cross-platform",
      "A Programming Language"
    ],
    "category": "plain"
  },
  "apollographql": {
    "label": "Apollographql",
    "tags": [
      "platform",
      "graphql",
      "api",
      "Apollo"
    ],
    "category": "original"
  },
  "appcelerator": {
    "label": "Appcelerator",
    "tags": [
      "app",
      "mobile"
    ],
    "category": "original"
  },
  "apple": {
    "label": "Apple",
    "tags": [
      "brand",
      "mobile"
    ],
    "category": "original"
  },
  "appwrite": {
    "label": "Appwrite",
    "tags": [
      "cloud",
      "platform",
      "server"
    ],
    "category": "original"
  },
  "archlinux": {
    "label": "Archlinux",
    "tags": [
      "linux",
      "distribution",
      "desktop"
    ],
    "category": "plain"
  },
  "arduino": {
    "label": "Arduino",
    "tags": [
      "microcontroller",
      "hardware"
    ],
    "category": "plain"
  },
  "argocd": {
    "label": "Argocd",
    "tags": [
      "gitops",
      "continuous-delivery"
    ],
    "category": "plain"
  },
  "arrow_back": {
    "label": "Arrow Back",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "arrow_downward": {
    "label": "Arrow Down",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "arrow_forward": {
    "label": "Arrow Forward",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "arrow_upward": {
    "label": "Arrow Up",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "artixlinux": {
    "label": "Artixlinux",
    "tags": [
      "linux",
      "os",
      "distribution",
      "desktop",
      "artix"
    ],
    "category": "plain"
  },
  "astro": {
    "label": "Astro",
    "tags": [
      "static site generator",
      "framework",
      "web-development"
    ],
    "category": "plain"
  },
  "atom": {
    "label": "Atom",
    "tags": [
      "editor"
    ],
    "category": "original"
  },
  "awk": {
    "label": "Awk",
    "tags": [
      "programming",
      "language",
      "unix",
      "the awk programming language"
    ],
    "category": "original"
  },
  "axios": {
    "label": "Axios",
    "tags": [
      "http",
      "promise",
      "nodejs"
    ],
    "category": "plain"
  },
  "azure": {
    "label": "Azure",
    "tags": [
      "cloud",
      "devops",
      "microsoftazure"
    ],
    "category": "plain"
  },
  "azuredevops": {
    "label": "Azuredevops",
    "tags": [
      "azure",
      "devops",
      "cloud",
      "version control",
      "vcs",
      "azure-devops"
    ],
    "category": "original"
  },
  "azuresqldatabase": {
    "label": "Azuresqldatabase",
    "tags": [
      "azure",
      "database",
      "tool",
      "sql",
      "azure-sql-database"
    ],
    "category": "original"
  },
  "babel": {
    "label": "Babel",
    "tags": [
      "javascript",
      "transpiler",
      "babeljs"
    ],
    "category": "plain"
  },
  "babylonjs": {
    "label": "Babylonjs",
    "tags": [
      "3d",
      "javascript",
      "library",
      "web",
      "babylon.js"
    ],
    "category": "plain"
  },
  "backbonejs": {
    "label": "Backbonejs",
    "tags": [
      "javascript",
      "framework"
    ],
    "category": "plain"
  },
  "ballerina": {
    "label": "Ballerina",
    "tags": [
      "java",
      "cloud",
      "server",
      "networking",
      "bal"
    ],
    "category": "original"
  },
  "bamboo": {
    "label": "Bamboo",
    "tags": [
      "platform",
      "integration",
      "server",
      "atlassianbamboo"
    ],
    "category": "original"
  },
  "bash": {
    "label": "Bash",
    "tags": [
      "shell",
      "command",
      "scripting",
      "bourneagainshell"
    ],
    "category": "plain"
  },
  "bazel": {
    "label": "Bazel",
    "tags": [
      "build",
      "automation",
      "open-source",
      "buildtoolbazel"
    ],
    "category": "plain"
  },
  "beats": {
    "label": "Beats",
    "tags": [
      "elastic",
      "data-transfer"
    ],
    "category": "original"
  },
  "behance": {
    "label": "Behance",
    "tags": [
      "social",
      "website"
    ],
    "category": "plain"
  },
  "bevyengine": {
    "label": "Bevyengine",
    "tags": [
      "game-engine",
      "game",
      "rust",
      "open-source",
      "bevy engine",
      "bevy"
    ],
    "category": "plain"
  },
  "biome": {
    "label": "Biome",
    "tags": [
      "linter",
      "javascript",
      "typescript",
      "code-quality",
      "coding-style",
      "format",
      "tool",
      "biomejs"
    ],
    "category": "original"
  },
  "bitbucket": {
    "label": "Bitbucket",
    "tags": [
      "version-control",
      "atlassianbitbucket"
    ],
    "category": "original"
  },
  "blazor": {
    "label": "Blazor",
    "tags": [
      "dotnet",
      ".net",
      "framework",
      "design",
      "ui"
    ],
    "category": "original"
  },
  "blender": {
    "label": "Blender",
    "tags": [
      "modelling",
      "python",
      "3d",
      "animation"
    ],
    "category": "original"
  },
  "bolt": {
    "label": "Bolt",
    "tags": [
      "performance",
      "speed",
      "lightning",
      "utility"
    ],
    "category": "material"
  },
  "bootstrap": {
    "label": "Bootstrap",
    "tags": [
      "css",
      "framework",
      "html",
      "javascript",
      "library"
    ],
    "category": "plain"
  },
  "bower": {
    "label": "Bower",
    "tags": [
      "package",
      "manager"
    ],
    "category": "plain"
  },
  "browserstack": {
    "label": "Browserstack",
    "tags": [
      "website",
      "app",
      "testing",
      "tool"
    ],
    "category": "plain"
  },
  "bulma": {
    "label": "Bulma",
    "tags": [
      "css",
      "framework",
      "bulmacss"
    ],
    "category": "plain"
  },
  "bun": {
    "label": "Bun",
    "tags": [
      "javascript",
      "zig",
      "language"
    ],
    "category": "plain"
  },
  "c": {
    "label": "C",
    "tags": [
      "language"
    ],
    "category": "original"
  },
  "cairo": {
    "label": "Cairo",
    "tags": [
      "graphic",
      "library",
      "c",
      "open-source",
      "cairographics"
    ],
    "category": "plain"
  },
  "cakephp": {
    "label": "Cakephp",
    "tags": [
      "framework"
    ],
    "category": "plain"
  },
  "call": {
    "label": "Call",
    "tags": [
      "communication",
      "phone",
      "contact"
    ],
    "category": "material"
  },
  "canva": {
    "label": "Canva",
    "tags": [
      "design"
    ],
    "category": "original"
  },
  "capacitor": {
    "label": "Capacitor",
    "tags": [
      "javascript",
      "js",
      "ionic",
      "framework",
      "universal",
      "capacitorjs"
    ],
    "category": "plain"
  },
  "carbon": {
    "label": "Carbon",
    "tags": [
      "programming",
      "language",
      "Carbon Language"
    ],
    "category": "original"
  },
  "cassandra": {
    "label": "Cassandra",
    "tags": [
      "nosql",
      "database",
      "open-source",
      "Apache Cassandra"
    ],
    "category": "plain"
  },
  "centos": {
    "label": "Centos",
    "tags": [
      "server",
      "linux"
    ],
    "category": "plain"
  },
  "ceylon": {
    "label": "Ceylon",
    "tags": [
      "language",
      "eclipseceylon",
      "ceylonlang"
    ],
    "category": "plain"
  },
  "chakraui": {
    "label": "Chakraui",
    "tags": [
      "ui",
      "library",
      "chakra ui"
    ],
    "category": "plain"
  },
  "chartjs": {
    "label": "Chartjs",
    "tags": [
      "javascript",
      "chart",
      "framework",
      "chart.js"
    ],
    "category": "plain"
  },
  "chat": {
    "label": "Chat",
    "tags": [
      "communication",
      "message",
      "contact"
    ],
    "category": "material"
  },
  "check": {
    "label": "Check",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "checklist": {
    "label": "Checklist",
    "tags": [
      "tasks",
      "list",
      "coverage",
      "cms",
      "utility"
    ],
    "category": "material"
  },
  "chevron_left": {
    "label": "Chevron Left",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "chevron_right": {
    "label": "Chevron Right",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "chrome": {
    "label": "Chrome",
    "tags": [
      "browser",
      "googlechrome"
    ],
    "category": "plain"
  },
  "circleci": {
    "label": "Circleci",
    "tags": [
      "integration",
      "platform"
    ],
    "category": "plain"
  },
  "clarity": {
    "label": "Clarity",
    "tags": [
      "programming",
      "language",
      "blockchain",
      "clarity-lang"
    ],
    "category": "plain"
  },
  "clickhouse": {
    "label": "Clickhouse",
    "tags": [
      "cloud",
      "column-oriented",
      "database",
      "warehouse"
    ],
    "category": "plain"
  },
  "clion": {
    "label": "Clion",
    "tags": [
      "jetbrains",
      "editor",
      "c",
      "c++",
      "cpp",
      "cplusplus"
    ],
    "category": "plain"
  },
  "clojure": {
    "label": "Clojure",
    "tags": [
      "language",
      "jvm"
    ],
    "category": "original"
  },
  "clojurescript": {
    "label": "Clojurescript",
    "tags": [
      "language"
    ],
    "category": "plain"
  },
  "close": {
    "label": "Close",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "cloudflare": {
    "label": "Cloudflare",
    "tags": [
      "web",
      "cdn",
      "dns",
      "proxy",
      "security"
    ],
    "category": "plain"
  },
  "cloudflareworkers": {
    "label": "Cloudflareworkers",
    "tags": [
      "platform",
      "serverless",
      "deploy",
      "performance",
      "javascript",
      "Cloudflare Workers"
    ],
    "category": "plain"
  },
  "cloudrun": {
    "label": "Cloudrun",
    "tags": [
      "platform",
      "serverless",
      "deploy",
      "cloud-computing-platform",
      "Cloud Run"
    ],
    "category": "plain"
  },
  "cmake": {
    "label": "Cmake",
    "tags": [
      "build"
    ],
    "category": "plain"
  },
  "cobol": {
    "label": "Cobol",
    "tags": [
      "language"
    ],
    "category": "original"
  },
  "codeac": {
    "label": "Codeac",
    "tags": [
      "platform",
      "integration",
      "codeacio"
    ],
    "category": "original"
  },
  "codecov": {
    "label": "Codecov",
    "tags": [
      "platform",
      "integration"
    ],
    "category": "plain"
  },
  "codeigniter": {
    "label": "Codeigniter",
    "tags": [
      "php",
      "framework"
    ],
    "category": "plain"
  },
  "codepen": {
    "label": "Codepen",
    "tags": [
      "social",
      "website",
      "editor"
    ],
    "category": "original"
  },
  "coffeescript": {
    "label": "Coffeescript",
    "tags": [
      "javascript",
      "transpiler",
      "language"
    ],
    "category": "original"
  },
  "composer": {
    "label": "Composer",
    "tags": [
      "package",
      "manager",
      "php"
    ],
    "category": "original"
  },
  "confluence": {
    "label": "Confluence",
    "tags": [
      "collaboration",
      "documentation",
      "wiki",
      "atlassianconfluence"
    ],
    "category": "plain"
  },
  "connected_tv": {
    "label": "Connected TV",
    "tags": [
      "device",
      "tv",
      "streaming",
      "utility"
    ],
    "category": "material"
  },
  "consul": {
    "label": "Consul",
    "tags": [
      "networking",
      "infrastructure",
      "security",
      "tool",
      "HashiCorp Consul"
    ],
    "category": "original"
  },
  "contao": {
    "label": "Contao",
    "tags": [
      "cms"
    ],
    "category": "original"
  },
  "corejs": {
    "label": "Corejs",
    "tags": [
      "javascript",
      "library",
      "polyfill",
      "tool",
      "core-js",
      "core.js"
    ],
    "category": "original"
  },
  "cosmosdb": {
    "label": "Cosmosdb",
    "tags": [
      "database",
      "nosql",
      "cloud",
      "azure",
      "azurecosmosdb"
    ],
    "category": "plain"
  },
  "couchbase": {
    "label": "Couchbase",
    "tags": [
      "database",
      "nosql",
      "cloud"
    ],
    "category": "original"
  },
  "couchdb": {
    "label": "Couchdb",
    "tags": [
      "database",
      "apachecouchdb"
    ],
    "category": "plain"
  },
  "cpanel": {
    "label": "Cpanel",
    "tags": [
      "hosting",
      "web hosting",
      "server",
      "control panel"
    ],
    "category": "original"
  },
  "cplusplus": {
    "label": "Cplusplus",
    "tags": [
      "language",
      "c++",
      "cpp"
    ],
    "category": "plain"
  },
  "crystal": {
    "label": "Crystal",
    "tags": [
      "programming",
      "language",
      "crystallang"
    ],
    "category": "original"
  },
  "csharp": {
    "label": "Csharp",
    "tags": [
      "language",
      "c#"
    ],
    "category": "plain"
  },
  "css3": {
    "label": "Css3",
    "tags": [
      "language",
      "programming",
      "cascadingstylesheets3"
    ],
    "category": "plain"
  },
  "cucumber": {
    "label": "Cucumber",
    "tags": [
      "framework",
      "cucumberjs"
    ],
    "category": "plain"
  },
  "cypressio": {
    "label": "Cypressio",
    "tags": [
      "testing",
      "framework",
      "cypress"
    ],
    "category": "plain"
  },
  "d3js": {
    "label": "D3js",
    "tags": [],
    "category": "plain"
  },
  "dart": {
    "label": "Dart",
    "tags": [
      "programming",
      "language",
      "googledart"
    ],
    "category": "plain"
  },
  "datadog": {
    "label": "Datadog",
    "tags": [
      "monitoring",
      "platform",
      "integration"
    ],
    "category": "original"
  },
  "datagrip": {
    "label": "Datagrip",
    "tags": [
      "jetbrains",
      "ide",
      "sql",
      "database"
    ],
    "category": "plain"
  },
  "dataspell": {
    "label": "Dataspell",
    "tags": [
      "jetbrains",
      "ide",
      "jupyter notebook",
      "data science"
    ],
    "category": "plain"
  },
  "datatables": {
    "label": "Datatables",
    "tags": [
      "css",
      "framework",
      "html",
      "javascript",
      "library"
    ],
    "category": "original"
  },
  "dbeaver": {
    "label": "Dbeaver",
    "tags": [
      "tool",
      "database"
    ],
    "category": "original"
  },
  "debian": {
    "label": "Debian",
    "tags": [
      "os",
      "server"
    ],
    "category": "plain"
  },
  "delphi": {
    "label": "Delphi",
    "tags": [
      "language",
      "embarcadero"
    ],
    "category": "plain"
  },
  "denojs": {
    "label": "Denojs",
    "tags": [
      "javascript",
      "rust",
      "runtime"
    ],
    "category": "original"
  },
  "detaspace": {
    "label": "Detaspace",
    "tags": [
      "cloud",
      "hosting",
      "server",
      "Deta",
      "Deta Space"
    ],
    "category": "original"
  },
  "devicon": {
    "label": "Devicon",
    "tags": [
      "iconset"
    ],
    "category": "plain"
  },
  "digitalocean": {
    "label": "Digitalocean",
    "tags": [
      "cloud",
      "hosting",
      "database",
      "storage"
    ],
    "category": "original"
  },
  "discloud": {
    "label": "Discloud",
    "tags": [
      "cloud",
      "hosting",
      "database",
      "storage"
    ],
    "category": "original"
  },
  "discord": {
    "label": "Discord",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "discordjs": {
    "label": "Discordjs",
    "tags": [
      "wrapper",
      "api_wrapper",
      "nodejs"
    ],
    "category": "plain"
  },
  "django": {
    "label": "Django",
    "tags": [],
    "category": "plain"
  },
  "djangorest": {
    "label": "Djangorest",
    "tags": [
      "framework",
      "rest",
      "api",
      "python",
      "web",
      "Django REST framework"
    ],
    "category": "plain"
  },
  "docker": {
    "label": "Docker",
    "tags": [
      "platform",
      "deploy"
    ],
    "category": "plain"
  },
  "doctrine": {
    "label": "Doctrine",
    "tags": [],
    "category": "plain"
  },
  "dot-net": {
    "label": "Dot Net",
    "tags": [
      "framework",
      "dotnet",
      ".net"
    ],
    "category": "plain"
  },
  "dotnetcore": {
    "label": "Dotnetcore",
    "tags": [
      "framework",
      ".netcore"
    ],
    "category": "plain"
  },
  "dovecot": {
    "label": "Dovecot",
    "tags": [
      "imap",
      "pop3",
      "e-mail"
    ],
    "category": "plain"
  },
  "download": {
    "label": "Download",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "dreamweaver": {
    "label": "Dreamweaver",
    "tags": [
      "web-development",
      "editor",
      "software",
      "tool",
      "Adobe Dreamweaver"
    ],
    "category": "plain"
  },
  "dribbble": {
    "label": "Dribbble",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "dropwizard": {
    "label": "Dropwizard",
    "tags": [
      "java",
      "framework"
    ],
    "category": "plain"
  },
  "drupal": {
    "label": "Drupal",
    "tags": [
      "cms"
    ],
    "category": "plain"
  },
  "duckdb": {
    "label": "Duckdb",
    "tags": [
      "database",
      "sql"
    ],
    "category": "plain"
  },
  "dyalog": {
    "label": "Dyalog",
    "tags": [
      "language"
    ],
    "category": "plain"
  },
  "dynamodb": {
    "label": "Dynamodb",
    "tags": [
      "key-value",
      "database",
      "java"
    ],
    "category": "plain"
  },
  "dynatrace": {
    "label": "Dynatrace",
    "tags": [
      "monitoring",
      "performance",
      "cloud"
    ],
    "category": "plain"
  },
  "eclipse": {
    "label": "Eclipse",
    "tags": [
      "editor",
      "IDE",
      "Eclipse IDE"
    ],
    "category": "original"
  },
  "ecto": {
    "label": "Ecto",
    "tags": [
      "data",
      "elixir",
      "integration",
      "query"
    ],
    "category": "original"
  },
  "elasticsearch": {
    "label": "Elasticsearch",
    "tags": [
      "elastic",
      "data",
      "logs"
    ],
    "category": "plain"
  },
  "electron": {
    "label": "Electron",
    "tags": [
      "framework",
      "electronjs"
    ],
    "category": "original"
  },
  "eleventy": {
    "label": "Eleventy",
    "tags": [
      "ssg",
      "static site generator",
      "11ty"
    ],
    "category": "plain"
  },
  "elixir": {
    "label": "Elixir",
    "tags": [
      "language",
      "elexirlang"
    ],
    "category": "plain"
  },
  "elm": {
    "label": "Elm",
    "tags": [
      "framework",
      "elmlang"
    ],
    "category": "plain"
  },
  "emacs": {
    "label": "Emacs",
    "tags": [
      "editor",
      "editingmacros"
    ],
    "category": "original"
  },
  "embeddedc": {
    "label": "Embeddedc",
    "tags": [
      "language",
      "programming"
    ],
    "category": "plain"
  },
  "ember": {
    "label": "Ember",
    "tags": [
      "framework",
      "javascript",
      "web-development",
      "build",
      "ember.js",
      "emberjs"
    ],
    "category": "plain"
  },
  "entityframeworkcore": {
    "label": "Entityframeworkcore",
    "tags": [
      "dotnet",
      ".net",
      "framework",
      "database",
      "ef core",
      "entity framework core"
    ],
    "category": "plain"
  },
  "envoy": {
    "label": "Envoy",
    "tags": [
      "proxy",
      "cloud",
      "envoyproxy"
    ],
    "category": "original"
  },
  "erlang": {
    "label": "Erlang",
    "tags": [],
    "category": "plain"
  },
  "eslint": {
    "label": "Eslint",
    "tags": [
      "linter",
      "javascript",
      "code-quality",
      "coding-style"
    ],
    "category": "plain"
  },
  "expo": {
    "label": "Expo",
    "tags": [
      "framework",
      "react",
      "react-native"
    ],
    "category": "original"
  },
  "express": {
    "label": "Express",
    "tags": [
      "framework",
      "expressjs"
    ],
    "category": "original"
  },
  "facebook": {
    "label": "Facebook",
    "tags": [
      "auth"
    ],
    "category": "plain"
  },
  "fastapi": {
    "label": "Fastapi",
    "tags": [
      "python",
      "framework"
    ],
    "category": "plain"
  },
  "fastify": {
    "label": "Fastify",
    "tags": [
      "framework",
      "web",
      "node.js",
      "javascript",
      "performance"
    ],
    "category": "plain"
  },
  "faunadb": {
    "label": "Faunadb",
    "tags": [
      "database",
      "fauna"
    ],
    "category": "original"
  },
  "feathersjs": {
    "label": "Feathersjs",
    "tags": [
      "framework",
      "rest"
    ],
    "category": "original"
  },
  "fedora": {
    "label": "Fedora",
    "tags": [
      "linux",
      "distribution",
      "desktop"
    ],
    "category": "plain"
  },
  "fiber": {
    "label": "Fiber",
    "tags": [
      "framework",
      "go",
      "web",
      "GoFiber"
    ],
    "category": "plain"
  },
  "figma": {
    "label": "Figma",
    "tags": [
      "design"
    ],
    "category": "plain"
  },
  "filamentphp": {
    "label": "Filamentphp",
    "tags": [
      "framework",
      "laravel"
    ],
    "category": "original"
  },
  "filezilla": {
    "label": "Filezilla",
    "tags": [
      "ftp"
    ],
    "category": "plain"
  },
  "firebase": {
    "label": "Firebase",
    "tags": [
      "auth",
      "hosting",
      "storage",
      "cloud"
    ],
    "category": "plain"
  },
  "firebird": {
    "label": "Firebird",
    "tags": [
      "database"
    ],
    "category": "plain"
  },
  "firefox": {
    "label": "Firefox",
    "tags": [
      "browser",
      "mozillafirefox"
    ],
    "category": "plain"
  },
  "first_page": {
    "label": "First Page",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "flask": {
    "label": "Flask",
    "tags": [
      "python",
      "framework"
    ],
    "category": "original"
  },
  "flutter": {
    "label": "Flutter",
    "tags": [
      "framework",
      "sdk"
    ],
    "category": "plain"
  },
  "forgejo": {
    "label": "Forgejo",
    "tags": [
      "software",
      "git",
      "version-control"
    ],
    "category": "plain"
  },
  "fortran": {
    "label": "Fortran",
    "tags": [
      "programming",
      "language"
    ],
    "category": "original"
  },
  "forum": {
    "label": "Forum",
    "tags": [
      "communication",
      "discussion"
    ],
    "category": "material"
  },
  "foundation": {
    "label": "Foundation",
    "tags": [
      "framework",
      "css"
    ],
    "category": "plain"
  },
  "framermotion": {
    "label": "Framermotion",
    "tags": [
      "library",
      "open-source",
      "react",
      "animation",
      "framer-motion",
      "framer"
    ],
    "category": "original"
  },
  "framework7": {
    "label": "Framework7",
    "tags": [
      "framework",
      "cross-platform",
      "development",
      "mobile",
      "android",
      "ios",
      "open-source"
    ],
    "category": "original"
  },
  "fsharp": {
    "label": "Fsharp",
    "tags": [
      "language",
      "f#"
    ],
    "category": "plain"
  },
  "fusion": {
    "label": "Fusion",
    "tags": [
      "design",
      "Autodesk Fusion",
      "Autodesk Fusion 360"
    ],
    "category": "plain"
  },
  "gardener": {
    "label": "Gardener",
    "tags": [
      "kubernetes",
      "cloud"
    ],
    "category": "plain"
  },
  "gatling": {
    "label": "Gatling",
    "tags": [
      "framework",
      "testing"
    ],
    "category": "original"
  },
  "gatsby": {
    "label": "Gatsby",
    "tags": [
      "reactjs",
      "framework",
      "gatsbyjs"
    ],
    "category": "original"
  },
  "gazebo": {
    "label": "Gazebo",
    "tags": [
      "robotics",
      "3d"
    ],
    "category": "plain"
  },
  "gcc": {
    "label": "Gcc",
    "tags": [
      "compiler",
      "linux",
      "gnucompilercollection"
    ],
    "category": "plain"
  },
  "gentoo": {
    "label": "Gentoo",
    "tags": [
      "linux",
      "distribution",
      "desktop"
    ],
    "category": "plain"
  },
  "ghost": {
    "label": "Ghost",
    "tags": [
      "cms"
    ],
    "category": "original"
  },
  "gift": {
    "label": "Gift",
    "tags": [
      "gift",
      "package",
      "box",
      "utility"
    ],
    "category": "material"
  },
  "gimp": {
    "label": "Gimp",
    "tags": [
      "graphic"
    ],
    "category": "plain"
  },
  "git": {
    "label": "Git",
    "tags": [
      "version-control"
    ],
    "category": "plain"
  },
  "gitbook": {
    "label": "Gitbook",
    "tags": [
      "documentation",
      "pages",
      "git",
      "markup"
    ],
    "category": "original"
  },
  "github": {
    "label": "Github",
    "tags": [
      "version-control"
    ],
    "category": "original"
  },
  "githubactions": {
    "label": "Githubactions",
    "tags": [
      "devops",
      "integration",
      "GitHub Actions"
    ],
    "category": "plain"
  },
  "githubcodespaces": {
    "label": "Githubcodespaces",
    "tags": [
      "development",
      "remote-development",
      "editor",
      "browser",
      "cloud",
      "GitHub Codespaces"
    ],
    "category": "plain"
  },
  "gitkraken": {
    "label": "Gitkraken",
    "tags": [
      "git",
      "version-control"
    ],
    "category": "original"
  },
  "gitlab": {
    "label": "Gitlab",
    "tags": [
      "version-control"
    ],
    "category": "plain"
  },
  "gitpod": {
    "label": "Gitpod",
    "tags": [
      "open-source",
      "remote-development",
      "cloud",
      "IDE",
      "gitpod-io"
    ],
    "category": "plain"
  },
  "gitter": {
    "label": "Gitter",
    "tags": [
      "social",
      "chat"
    ],
    "category": "plain"
  },
  "gleam": {
    "label": "Gleam",
    "tags": [
      "language",
      "programming"
    ],
    "category": "plain"
  },
  "glitch": {
    "label": "Glitch",
    "tags": [
      "web-apps",
      "online-platform",
      "programming-environment",
      "collaborative-environment"
    ],
    "category": "plain"
  },
  "go": {
    "label": "Go",
    "tags": [
      "language",
      "golang"
    ],
    "category": "plain"
  },
  "godot": {
    "label": "Godot",
    "tags": [
      "game-engine",
      "open-source"
    ],
    "category": "plain"
  },
  "goland": {
    "label": "Goland",
    "tags": [
      "jetbrains",
      "ide",
      "go"
    ],
    "category": "plain"
  },
  "google": {
    "label": "Google",
    "tags": [
      "auth"
    ],
    "category": "plain"
  },
  "googleanalytics": {
    "label": "Google Analytics",
    "tags": [
      "analytics",
      "google",
      "brand"
    ],
    "category": "tools"
  },
  "googlecloud": {
    "label": "Googlecloud",
    "tags": [
      "google",
      "cloud"
    ],
    "category": "plain"
  },
  "googlecolab": {
    "label": "Googlecolab",
    "tags": [
      "cloud-computing-platform",
      "data science",
      "google",
      "machine-learning",
      "python",
      "virtual machine",
      "googlecolaboratory"
    ],
    "category": "plain"
  },
  "gradle": {
    "label": "Gradle",
    "tags": [
      "open-source",
      "task-runner",
      "apachegradle",
      "gradlebuildtool"
    ],
    "category": "original"
  },
  "grafana": {
    "label": "Grafana",
    "tags": [
      "monitoring",
      "analytics",
      "metrics",
      "logs",
      "visualization",
      "web-application"
    ],
    "category": "plain"
  },
  "grails": {
    "label": "Grails",
    "tags": [
      "framework",
      "groovy",
      "web-development",
      "jvm",
      "build",
      "Grails Framework"
    ],
    "category": "plain"
  },
  "graphql": {
    "label": "Graphql",
    "tags": [
      "language",
      "data",
      "query"
    ],
    "category": "plain"
  },
  "groovy": {
    "label": "Groovy",
    "tags": [
      "programming",
      "language",
      "jvm",
      "groovylang",
      "apachegroovy"
    ],
    "category": "plain"
  },
  "grpc": {
    "label": "Grpc",
    "tags": [
      "programming",
      "c++",
      "java",
      "python",
      "go",
      "library",
      "grpcio",
      "Google Remote Procedure Call"
    ],
    "category": "plain"
  },
  "grunt": {
    "label": "Grunt",
    "tags": [
      "task-runner",
      "nodejs",
      "gruntjs"
    ],
    "category": "plain"
  },
  "gulp": {
    "label": "Gulp",
    "tags": [
      "task-runner",
      "nodejs",
      "gulpjs"
    ],
    "category": "plain"
  },
  "hadoop": {
    "label": "Hadoop",
    "tags": [
      "framework",
      "big data",
      "open-source",
      "software",
      "library",
      "java",
      "Apache Hadoop"
    ],
    "category": "plain"
  },
  "handlebars": {
    "label": "Handlebars",
    "tags": [
      "framework",
      "handlebarsjs"
    ],
    "category": "original"
  },
  "harbor": {
    "label": "Harbor",
    "tags": [
      "docker",
      "artifact",
      "oci",
      "registry"
    ],
    "category": "plain"
  },
  "hardhat": {
    "label": "Hardhat",
    "tags": [
      "ethereum",
      "development",
      "solidity",
      "javascript",
      "typescript"
    ],
    "category": "plain"
  },
  "harvester": {
    "label": "Harvester",
    "tags": [
      "kubernetes",
      "operating-system",
      "hypervisor",
      "rancher",
      "harvesterhci"
    ],
    "category": "original"
  },
  "haskell": {
    "label": "Haskell",
    "tags": [
      "language",
      "functional"
    ],
    "category": "plain"
  },
  "haxe": {
    "label": "Haxe",
    "tags": [
      "language"
    ],
    "category": "plain"
  },
  "helm": {
    "label": "Helm",
    "tags": [
      "package",
      "manager",
      "kubernetes"
    ],
    "category": "original"
  },
  "heroku": {
    "label": "Heroku",
    "tags": [
      "cloud"
    ],
    "category": "plain"
  },
  "hibernate": {
    "label": "Hibernate",
    "tags": [
      "database",
      "framework",
      "java"
    ],
    "category": "plain"
  },
  "home": {
    "label": "Home",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "homebrew": {
    "label": "Homebrew",
    "tags": [
      "package",
      "manager",
      "linux",
      "apple",
      "os"
    ],
    "category": "plain"
  },
  "hoppscotch": {
    "label": "Hoppscotch",
    "tags": [
      "rest",
      "testing",
      "api"
    ],
    "category": "plain"
  },
  "html5": {
    "label": "Html5",
    "tags": [
      "programming",
      "language",
      "hypertextmarkdownlanguage5"
    ],
    "category": "plain"
  },
  "htmx": {
    "label": "Htmx",
    "tags": [
      "framework",
      "web",
      "html",
      "ui",
      "html ui framework"
    ],
    "category": "plain"
  },
  "hugo": {
    "label": "Hugo",
    "tags": [
      "framework",
      "ssg",
      "static-site-generator",
      "go",
      "html",
      "css",
      "gohugo"
    ],
    "category": "plain"
  },
  "hyperv": {
    "label": "Hyperv",
    "tags": [
      "hypervisor",
      "operating-system",
      "hyper-v"
    ],
    "category": "plain"
  },
  "ie10": {
    "label": "Ie10",
    "tags": [
      "browser",
      "internetexplorer10"
    ],
    "category": "original"
  },
  "ifttt": {
    "label": "Ifttt",
    "tags": [
      "automation",
      "applets",
      "programming",
      "ifthisthenthat"
    ],
    "category": "original"
  },
  "illustrator": {
    "label": "Illustrator",
    "tags": [
      "editor",
      "vector",
      "adobeillustrator"
    ],
    "category": "plain"
  },
  "inertiajs": {
    "label": "Inertiajs",
    "tags": [
      "javascript",
      "js",
      "library",
      "inertia.js"
    ],
    "category": "plain"
  },
  "influxdb": {
    "label": "Influxdb",
    "tags": [
      "database",
      "monitoring",
      "open-source",
      "api"
    ],
    "category": "original"
  },
  "inkscape": {
    "label": "Inkscape",
    "tags": [
      "editor",
      "vector"
    ],
    "category": "plain"
  },
  "insomnia": {
    "label": "Insomnia",
    "tags": [
      "open-source",
      "Rest API",
      "Soap API",
      "JSON-XML",
      "Insomnia Rest Client"
    ],
    "category": "plain"
  },
  "instagram": {
    "label": "Instagram",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "intellij": {
    "label": "Intellij",
    "tags": [
      "jetbrains",
      "editor",
      "java",
      "intellijidea"
    ],
    "category": "plain"
  },
  "ionic": {
    "label": "Ionic",
    "tags": [
      "framework"
    ],
    "category": "original"
  },
  "jaegertracing": {
    "label": "Jaegertracing",
    "tags": [
      "monitoring",
      "tracing",
      "jaeger"
    ],
    "category": "plain"
  },
  "jamstack": {
    "label": "Jamstack",
    "tags": [
      "javascript",
      "markup"
    ],
    "category": "original"
  },
  "jasmine": {
    "label": "Jasmine",
    "tags": [
      "testing",
      "jasminejs"
    ],
    "category": "original"
  },
  "java": {
    "label": "Java",
    "tags": [
      "programming",
      "language",
      "jvm"
    ],
    "category": "plain"
  },
  "javascript": {
    "label": "Javascript",
    "tags": [
      "programming",
      "language",
      "js",
      "ecmascript"
    ],
    "category": "plain"
  },
  "jeet": {
    "label": "Jeet",
    "tags": [
      "framework",
      "css"
    ],
    "category": "plain"
  },
  "jekyll": {
    "label": "Jekyll",
    "tags": [
      "ruby",
      "blog",
      "jestjs"
    ],
    "category": "plain"
  },
  "jenkins": {
    "label": "Jenkins",
    "tags": [
      "platform",
      "integration",
      "server",
      "hudson"
    ],
    "category": "plain"
  },
  "jest": {
    "label": "Jest",
    "tags": [
      "testing",
      "javascript",
      "jestjs"
    ],
    "category": "plain"
  },
  "jetbrains": {
    "label": "Jetbrains",
    "tags": [
      "ide",
      "intellijsoftware"
    ],
    "category": "plain"
  },
  "jetpackcompose": {
    "label": "Jetpackcompose",
    "tags": [
      "framework",
      "language",
      "kotlin",
      "android"
    ],
    "category": "plain"
  },
  "jhipster": {
    "label": "Jhipster",
    "tags": [
      "development",
      "framework",
      "java",
      "platform",
      "web",
      "web-application",
      "web-development"
    ],
    "category": "plain"
  },
  "jira": {
    "label": "Jira",
    "tags": [
      "platform",
      "organize",
      "atlassianjira"
    ],
    "category": "plain"
  },
  "jiraalign": {
    "label": "Jiraalign",
    "tags": [
      "development",
      "integration",
      "software",
      "Jira Align"
    ],
    "category": "plain"
  },
  "jquery": {
    "label": "Jquery",
    "tags": [
      "library",
      "javascript",
      "jqueryjs"
    ],
    "category": "plain"
  },
  "json": {
    "label": "Json",
    "tags": [
      "format",
      "standard",
      "file-format",
      "object-notation",
      "JavaScript Object Notation"
    ],
    "category": "plain"
  },
  "jule": {
    "label": "Jule",
    "tags": [
      "programming",
      "language",
      "julelang"
    ],
    "category": "original"
  },
  "julia": {
    "label": "Julia",
    "tags": [
      "programming",
      "language",
      "julialang"
    ],
    "category": "plain"
  },
  "junit": {
    "label": "Junit",
    "tags": [
      "testing",
      "framework",
      "java"
    ],
    "category": "plain"
  },
  "jupyter": {
    "label": "Jupyter",
    "tags": [
      "programming",
      "language",
      "jupyternotebook"
    ],
    "category": "plain"
  },
  "k3os": {
    "label": "K3os",
    "tags": [
      "kubernetes",
      "operating-system",
      "k3s",
      "rancher"
    ],
    "category": "original"
  },
  "k3s": {
    "label": "K3s",
    "tags": [
      "kubernetes",
      "container",
      "platform"
    ],
    "category": "original"
  },
  "k6": {
    "label": "K6",
    "tags": [
      "testing",
      "performance",
      "load"
    ],
    "category": "original"
  },
  "kaggle": {
    "label": "Kaggle",
    "tags": [
      "platform",
      "auth",
      "machine-learning"
    ],
    "category": "original"
  },
  "kaldi": {
    "label": "Kaldi",
    "tags": [
      "audio",
      "open-source",
      "library"
    ],
    "category": "plain"
  },
  "kalilinux": {
    "label": "Kalilinux",
    "tags": [
      "linux",
      "operating-system",
      "security",
      "kali"
    ],
    "category": "original"
  },
  "karatelabs": {
    "label": "Karatelabs",
    "tags": [
      "framework",
      "testing",
      "karate"
    ],
    "category": "plain"
  },
  "karma": {
    "label": "Karma",
    "tags": [
      "testing",
      "test-runner",
      "karmarunner",
      "karmajs"
    ],
    "category": "plain"
  },
  "kdeneon": {
    "label": "Kdeneon",
    "tags": [
      "linux",
      "operating system",
      "open-source"
    ],
    "category": "plain"
  },
  "keras": {
    "label": "Keras",
    "tags": [
      "machine-learning",
      "python",
      "library"
    ],
    "category": "plain"
  },
  "keyboard_arrow_down": {
    "label": "Arrow Down (small)",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "keyboard_arrow_up": {
    "label": "Arrow Up (small)",
    "tags": [
      "navigation",
      "arrow",
      "utility"
    ],
    "category": "material"
  },
  "kibana": {
    "label": "Kibana",
    "tags": [
      "elastic",
      "dashboard"
    ],
    "category": "plain"
  },
  "knexjs": {
    "label": "Knexjs",
    "tags": [
      "database",
      "query",
      "sql",
      "javascript",
      "library"
    ],
    "category": "original"
  },
  "knockout": {
    "label": "Knockout",
    "tags": [
      "framework",
      "javascript",
      "knockoutjs"
    ],
    "category": "plain-wordmark"
  },
  "kotlin": {
    "label": "Kotlin",
    "tags": [
      "language",
      "jetbrains",
      "jvm",
      "kotlinlang"
    ],
    "category": "plain"
  },
  "krakenjs": {
    "label": "Krakenjs",
    "tags": [
      "nodejs",
      "framework",
      "kraken"
    ],
    "category": "plain"
  },
  "ktor": {
    "label": "Ktor",
    "tags": [
      "jetbrains",
      "kotlin",
      "framework"
    ],
    "category": "plain"
  },
  "kubeflow": {
    "label": "Kubeflow",
    "tags": [
      "kubernetes",
      "deployment",
      "machine-learning"
    ],
    "category": "plain"
  },
  "kubernetes": {
    "label": "Kubernetes",
    "tags": [
      "container",
      "deployment"
    ],
    "category": "plain"
  },
  "labview": {
    "label": "Labview",
    "tags": [
      "language"
    ],
    "category": "plain"
  },
  "laminas": {
    "label": "Laminas",
    "tags": [
      "php",
      "framework",
      "web",
      "mvc",
      "middleware",
      "Laminas Project",
      "Zend Framework"
    ],
    "category": "original"
  },
  "langchain": {
    "label": "LangChain",
    "tags": [
      "ai",
      "llm",
      "framework",
      "brand"
    ],
    "category": "tools"
  },
  "language": {
    "label": "Website",
    "tags": [
      "communication",
      "website",
      "globe",
      "contact"
    ],
    "category": "material"
  },
  "laravel": {
    "label": "Laravel",
    "tags": [
      "php",
      "framework"
    ],
    "category": "original"
  },
  "laraveljetstream": {
    "label": "Laraveljetstream",
    "tags": [
      "php",
      "laravel",
      "tailwind",
      "scaffolding",
      "jetstream",
      "Laravel Jetstream"
    ],
    "category": "original"
  },
  "last_page": {
    "label": "Last Page",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "latex": {
    "label": "Latex",
    "tags": [
      "latex3",
      "latex2e",
      "markup",
      "tex",
      "typesetting-system"
    ],
    "category": "original"
  },
  "leetcode": {
    "label": "Leetcode",
    "tags": [
      "online-platform",
      "coding-platform",
      "platform",
      "coding",
      "dsa",
      "interview-preparation"
    ],
    "category": "plain"
  },
  "less": {
    "label": "Less",
    "tags": [
      "css",
      "pre-processor",
      "lesscss"
    ],
    "category": "plain-wordmark"
  },
  "libgdx": {
    "label": "Libgdx",
    "tags": [
      "framework",
      "java",
      "game-development",
      "cross-platform",
      "open-source"
    ],
    "category": "plain"
  },
  "linkedin": {
    "label": "Linkedin",
    "tags": [
      "social",
      "auth"
    ],
    "category": "plain"
  },
  "linux": {
    "label": "Linux",
    "tags": [
      "os"
    ],
    "category": "plain"
  },
  "linuxmint": {
    "label": "Linuxmint",
    "tags": [
      "os",
      "linux"
    ],
    "category": "plain"
  },
  "liquibase": {
    "label": "Liquibase",
    "tags": [
      "tool",
      "database"
    ],
    "category": "original"
  },
  "livewire": {
    "label": "Livewire",
    "tags": [
      "framework",
      "laravel",
      "php",
      "open-source",
      "laravel-livewire"
    ],
    "category": "plain"
  },
  "llvm": {
    "label": "Llvm",
    "tags": [
      "compiler",
      "framework",
      "c++",
      "open-source",
      "Low Level Virtual Machine"
    ],
    "category": "plain"
  },
  "location_on": {
    "label": "Location",
    "tags": [
      "communication",
      "map",
      "contact"
    ],
    "category": "material"
  },
  "lodash": {
    "label": "Lodash",
    "tags": [
      "javascript",
      "framework"
    ],
    "category": "plain"
  },
  "logstash": {
    "label": "Logstash",
    "tags": [
      "logs",
      "elastic"
    ],
    "category": "plain"
  },
  "love2d": {
    "label": "Love2d",
    "tags": [
      "programming",
      "game-engine",
      "löve"
    ],
    "category": "plain"
  },
  "lua": {
    "label": "Lua",
    "tags": [
      "programming",
      "language",
      "object-oriented",
      "scripting",
      "procedural",
      "prototype-based",
      "functional",
      "lualang"
    ],
    "category": "plain"
  },
  "lumen": {
    "label": "Lumen",
    "tags": [
      "laravel",
      "php",
      "framework",
      "micro-framework",
      "Laravel Lumen",
      "Lumen Laravel",
      "Laravel Lumen Framework",
      "laravel.lumen"
    ],
    "category": "original"
  },
  "magento": {
    "label": "Magento",
    "tags": [
      "php",
      "framework"
    ],
    "category": "original"
  },
  "mail": {
    "label": "Mail",
    "tags": [
      "communication",
      "email",
      "contact"
    ],
    "category": "material"
  },
  "mapbox": {
    "label": "Mapbox",
    "tags": [
      "map",
      "navigation",
      "data"
    ],
    "category": "original"
  },
  "mariadb": {
    "label": "Mariadb",
    "tags": [
      "database",
      "sql",
      "open-source"
    ],
    "category": "original"
  },
  "markdown": {
    "label": "Markdown",
    "tags": [
      "markup",
      "language",
      "md"
    ],
    "category": "original"
  },
  "materializecss": {
    "label": "Materializecss",
    "tags": [
      "framework",
      "css",
      "design",
      "material-design",
      "materialize",
      "materialize-css",
      "materialize css"
    ],
    "category": "plain"
  },
  "materialui": {
    "label": "Materialui",
    "tags": [
      "framework",
      "design",
      "ui",
      "mui"
    ],
    "category": "plain"
  },
  "matlab": {
    "label": "Matlab",
    "tags": [
      "programming",
      "language"
    ],
    "category": "plain"
  },
  "matplotlib": {
    "label": "Matplotlib",
    "tags": [
      "plotting",
      "library",
      "math",
      "visualization",
      "python",
      "api"
    ],
    "category": "plain"
  },
  "mattermost": {
    "label": "Mattermost",
    "tags": [
      "app",
      "chat",
      "collaboration",
      "open-source",
      "platform"
    ],
    "category": "original"
  },
  "maven": {
    "label": "Maven",
    "tags": [
      "build",
      "apachemaven",
      "mvn"
    ],
    "category": "plain"
  },
  "maya": {
    "label": "Maya",
    "tags": [
      "mel",
      "pymel",
      "python",
      "3d",
      "programming",
      "vfx",
      "graphic",
      "graphics",
      "game",
      "animation"
    ],
    "category": "plain"
  },
  "mcp": {
    "label": "MCP",
    "tags": [
      "ai",
      "llm",
      "protocol",
      "brand"
    ],
    "category": "tools"
  },
  "medium": {
    "label": "Medium",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "memcached": {
    "label": "Memcached",
    "tags": [
      "data",
      "database",
      "nosql"
    ],
    "category": "plain"
  },
  "menu": {
    "label": "Menu",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "mercurial": {
    "label": "Mercurial",
    "tags": [
      "version-control"
    ],
    "category": "plain"
  },
  "meteor": {
    "label": "Meteor",
    "tags": [
      "javascript",
      "framework",
      "meteorjs"
    ],
    "category": "plain"
  },
  "microsoftsqlserver": {
    "label": "Microsoftsqlserver",
    "tags": [
      "database",
      "sql",
      "db",
      "msql",
      "mssql",
      "Microsoft SQL Server"
    ],
    "category": "plain"
  },
  "minitab": {
    "label": "Minitab",
    "tags": [
      "package",
      "statistics"
    ],
    "category": "plain"
  },
  "mithril": {
    "label": "Mithril",
    "tags": [
      "javascript",
      "framework",
      "frontend",
      "js",
      "mithril.js"
    ],
    "category": "original"
  },
  "mobx": {
    "label": "Mobx",
    "tags": [
      "state-management",
      "testing",
      "reactjs",
      "nodejs",
      "mobxjs"
    ],
    "category": "plain"
  },
  "mocha": {
    "label": "Mocha",
    "tags": [
      "testing"
    ],
    "category": "plain"
  },
  "modx": {
    "label": "Modx",
    "tags": [
      "cms",
      "php",
      "framework"
    ],
    "category": "plain"
  },
  "moleculer": {
    "label": "Moleculer",
    "tags": [
      "nodejs",
      "javascript",
      "js",
      "microservices",
      "micro-services",
      "framework",
      "moleculerjs",
      "moleculer.js"
    ],
    "category": "original"
  },
  "mongodb": {
    "label": "Mongodb",
    "tags": [
      "database"
    ],
    "category": "plain"
  },
  "mongoose": {
    "label": "Mongoose",
    "tags": [
      "data-model",
      "nodejs",
      "mongoosejs"
    ],
    "category": "original"
  },
  "monogame": {
    "label": "Monogame",
    "tags": [
      "engine",
      "game-engine",
      "C#",
      "c-sharp",
      "csharp"
    ],
    "category": "original"
  },
  "moodle": {
    "label": "Moodle",
    "tags": [
      "platform"
    ],
    "category": "plain"
  },
  "more_horiz": {
    "label": "More (horizontal)",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "more_vert": {
    "label": "More (vertical)",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "msdos": {
    "label": "Msdos",
    "tags": [
      "os",
      "microsoftdiskoperatingsystem"
    ],
    "category": "plain"
  },
  "mysql": {
    "label": "Mysql",
    "tags": [
      "database",
      "language",
      "mystructuredquerylanguage"
    ],
    "category": "original"
  },
  "nano": {
    "label": "Nano",
    "tags": [
      "text editor",
      "editor",
      "GNU",
      "terminal",
      "gnu-nano",
      "GNU nano"
    ],
    "category": "plain"
  },
  "nats": {
    "label": "Nats",
    "tags": [
      "streaming",
      "open-source",
      "go",
      "nats-io",
      "nats.io",
      "NATS-io",
      "NATS.io"
    ],
    "category": "plain"
  },
  "neo4j": {
    "label": "Neo4j",
    "tags": [
      "database"
    ],
    "category": "plain"
  },
  "neovim": {
    "label": "Neovim",
    "tags": [
      "text editor",
      "editor",
      "ide",
      "IDE",
      "open-source"
    ],
    "category": "plain"
  },
  "nestjs": {
    "label": "Nestjs",
    "tags": [
      "framework"
    ],
    "category": "original"
  },
  "netbeans": {
    "label": "Netbeans",
    "tags": [
      "ide",
      "java",
      "open-source"
    ],
    "category": "plain"
  },
  "netbox": {
    "label": "Netbox",
    "tags": [
      "network",
      "automation",
      "infrastructure",
      "open-source"
    ],
    "category": "plain"
  },
  "netlify": {
    "label": "Netlify",
    "tags": [
      "cloud hosting",
      "serverless",
      "dynamic websites",
      "web applications",
      "open-source"
    ],
    "category": "plain"
  },
  "networkx": {
    "label": "Networkx",
    "tags": [
      "graph",
      "library",
      "python"
    ],
    "category": "plain"
  },
  "newrelic": {
    "label": "Newrelic",
    "tags": [
      "monitoring",
      "observability",
      "analysis"
    ],
    "category": "plain"
  },
  "nextjs": {
    "label": "Nextjs",
    "tags": [
      "framework"
    ],
    "category": "plain"
  },
  "nginx": {
    "label": "Nginx",
    "tags": [
      "server"
    ],
    "category": "original"
  },
  "ngrok": {
    "label": "Ngrok",
    "tags": [
      "networking",
      "server"
    ],
    "category": "original"
  },
  "ngrx": {
    "label": "Ngrx",
    "tags": [
      "state-management",
      "angular",
      "redux",
      "store",
      "javascript"
    ],
    "category": "plain"
  },
  "nhibernate": {
    "label": "Nhibernate",
    "tags": [
      "library",
      "dotnet",
      ".net",
      "object-relational mapper",
      "orm",
      "C#",
      "c-sharp"
    ],
    "category": "plain"
  },
  "nim": {
    "label": "Nim",
    "tags": [
      "programming",
      "functional",
      "object-oriented",
      "procedural",
      "nimlang"
    ],
    "category": "plain"
  },
  "nimble": {
    "label": "Nimble",
    "tags": [
      "package-manager"
    ],
    "category": "plain"
  },
  "nixos": {
    "label": "Nixos",
    "tags": [
      "os"
    ],
    "category": "plain"
  },
  "nodejs": {
    "label": "Nodejs",
    "tags": [
      "javascript",
      "language"
    ],
    "category": "plain"
  },
  "nodemon": {
    "label": "Nodemon",
    "tags": [
      "nodejs",
      "tool",
      "javascript",
      "nodemonjs"
    ],
    "category": "plain"
  },
  "nodered": {
    "label": "Nodered",
    "tags": [
      "programming",
      "tool",
      "node-red"
    ],
    "category": "plain"
  },
  "nodewebkit": {
    "label": "Nodewebkit",
    "tags": [
      "nwjs"
    ],
    "category": "plain"
  },
  "nomad": {
    "label": "Nomad",
    "tags": [
      "container",
      "virtual machine",
      "deployment",
      "HashiCorp Nomad"
    ],
    "category": "original"
  },
  "norg": {
    "label": "Norg",
    "tags": [
      "note-taking",
      "organization",
      "neorg"
    ],
    "category": "plain"
  },
  "notion": {
    "label": "Notion",
    "tags": [
      "project-management"
    ],
    "category": "plain"
  },
  "npm": {
    "label": "Npm",
    "tags": [
      "package",
      "manager",
      "npmjs",
      "nodepackagemanager"
    ],
    "category": "plain"
  },
  "npss": {
    "label": "Npss",
    "tags": [],
    "category": "plain"
  },
  "nuget": {
    "label": "Nuget",
    "tags": [
      "package",
      "manager"
    ],
    "category": "original"
  },
  "numpy": {
    "label": "Numpy",
    "tags": [
      "library",
      "python"
    ],
    "category": "plain"
  },
  "nuxt": {
    "label": "Nuxt",
    "tags": [
      "js",
      "javascript",
      "framework",
      "fullstack",
      "vuejs"
    ],
    "category": "original"
  },
  "nuxtjs": {
    "label": "Nuxtjs",
    "tags": [
      "js",
      "javascript",
      "framework",
      "frontend",
      "vuejs"
    ],
    "category": "plain"
  },
  "oauth": {
    "label": "Oauth",
    "tags": [
      "authentication",
      "security"
    ],
    "category": "plain"
  },
  "objectivec": {
    "label": "Objectivec",
    "tags": [
      "programming",
      "language"
    ],
    "category": "plain"
  },
  "ocaml": {
    "label": "Ocaml",
    "tags": [
      "programming",
      "language"
    ],
    "category": "plain"
  },
  "ohmyzsh": {
    "label": "Ohmyzsh",
    "tags": [
      "shell",
      "script",
      "scripting",
      "language",
      "command",
      "omz",
      "ohmyz.sh",
      "Oh My Zsh"
    ],
    "category": "plain"
  },
  "okta": {
    "label": "Okta",
    "tags": [
      "auth",
      "security",
      "okta developer"
    ],
    "category": "plain"
  },
  "ollama": {
    "label": "Ollama",
    "tags": [
      "ai",
      "llm",
      "brand"
    ],
    "category": "tools"
  },
  "open_in_new": {
    "label": "Open in New",
    "tags": [
      "navigation",
      "utility",
      "external-link"
    ],
    "category": "material"
  },
  "openal": {
    "label": "Openal",
    "tags": [
      "library",
      "audio",
      "game",
      "3d"
    ],
    "category": "plain"
  },
  "openapi": {
    "label": "Openapi",
    "tags": [
      "specification",
      "api",
      "open-source"
    ],
    "category": "plain"
  },
  "opencl": {
    "label": "Opencl",
    "tags": [
      "framework",
      "language",
      "heterogeneous-computing",
      "cpp",
      "api",
      "khronos",
      "programming"
    ],
    "category": "plain"
  },
  "opencv": {
    "label": "Opencv",
    "tags": [
      "library",
      "c/c++",
      "computer-vision"
    ],
    "category": "plain"
  },
  "opengl": {
    "label": "Opengl",
    "tags": [
      "library",
      "graphics",
      "game",
      "3d",
      "opengraphicslibrary"
    ],
    "category": "plain"
  },
  "openstack": {
    "label": "Openstack",
    "tags": [
      "infrastructure-as-a-service",
      "cloud-computing-platform"
    ],
    "category": "original"
  },
  "opensuse": {
    "label": "Opensuse",
    "tags": [
      "linux",
      "distribution",
      "desktop"
    ],
    "category": "original"
  },
  "opentelemetry": {
    "label": "Opentelemetry",
    "tags": [
      "telemetry"
    ],
    "category": "plain"
  },
  "opera": {
    "label": "Opera",
    "tags": [
      "browser"
    ],
    "category": "plain"
  },
  "oracle": {
    "label": "Oracle",
    "tags": [
      "database",
      "oracledatabase"
    ],
    "category": "original"
  },
  "ory": {
    "label": "Ory",
    "tags": [
      "library",
      "open-source",
      "security"
    ],
    "category": "original"
  },
  "p5js": {
    "label": "P5js",
    "tags": [
      "javascript",
      "js",
      "library",
      "p5.js"
    ],
    "category": "original"
  },
  "packer": {
    "label": "Packer",
    "tags": [
      "infrastructure",
      "infrastructure-as-code",
      "continuous-delivery"
    ],
    "category": "plain"
  },
  "pandas": {
    "label": "Pandas",
    "tags": [
      "library",
      "python"
    ],
    "category": "plain"
  },
  "passport": {
    "label": "Passport",
    "tags": [
      "authentication",
      "security",
      "passportjs"
    ],
    "category": "plain"
  },
  "perl": {
    "label": "Perl",
    "tags": [
      "programming",
      "language"
    ],
    "category": "plain"
  },
  "pfsense": {
    "label": "Pfsense",
    "tags": [
      "cloud",
      "network",
      "open-source",
      "security",
      "software",
      "pfSense"
    ],
    "category": "original"
  },
  "phalcon": {
    "label": "Phalcon",
    "tags": [
      "php",
      "framework"
    ],
    "category": "plain"
  },
  "phoenix": {
    "label": "Phoenix",
    "tags": [
      "framework",
      "build",
      "web",
      "web-development",
      "development",
      "elixir",
      "Phoenix Framework"
    ],
    "category": "original"
  },
  "photonengine": {
    "label": "Photonengine",
    "tags": [
      "game",
      "game-engine",
      "photon"
    ],
    "category": "plain"
  },
  "photoshop": {
    "label": "Photoshop",
    "tags": [
      "editor",
      "graphic",
      "adobephotoshop"
    ],
    "category": "plain"
  },
  "php": {
    "label": "Php",
    "tags": [
      "programming",
      "language",
      "PHP Hypertext Preprocessor",
      "Personal Home Page"
    ],
    "category": "plain"
  },
  "phpstorm": {
    "label": "Phpstorm",
    "tags": [
      "jetbrains",
      "editor",
      "php",
      "web",
      "html"
    ],
    "category": "plain"
  },
  "pinterest": {
    "label": "Pinterest",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "pixijs": {
    "label": "Pixijs",
    "tags": [
      "animation",
      "graphics",
      "html",
      "javascript",
      "library",
      "visualization",
      "ui"
    ],
    "category": "plain"
  },
  "playwright": {
    "label": "Playwright",
    "tags": [
      "testing",
      "framework"
    ],
    "category": "plain"
  },
  "plotly": {
    "label": "Plotly",
    "tags": [
      "frontend",
      "machine-learning",
      "dashboard"
    ],
    "category": "plain"
  },
  "pm2": {
    "label": "Pm2",
    "tags": [
      "nodejs",
      "javascript",
      "js",
      "manager",
      "monitoring"
    ],
    "category": "plain"
  },
  "pnpm": {
    "label": "Pnpm",
    "tags": [
      "package",
      "manager",
      "performant npm"
    ],
    "category": "plain"
  },
  "podman": {
    "label": "Podman",
    "tags": [
      "container",
      "pods",
      "docker"
    ],
    "category": "plain"
  },
  "poetry": {
    "label": "Poetry",
    "tags": [
      "package-manager",
      "python",
      "python-poetry"
    ],
    "category": "original"
  },
  "polygon": {
    "label": "Polygon",
    "tags": [
      "ethereum",
      "erc20",
      "blockchain"
    ],
    "category": "plain"
  },
  "portainer": {
    "label": "Portainer",
    "tags": [
      "docker",
      "kubernetes",
      "orchestrator"
    ],
    "category": "original"
  },
  "postcss": {
    "label": "Postcss",
    "tags": [
      "pre-processor",
      "css",
      "framework"
    ],
    "category": "original"
  },
  "postgresql": {
    "label": "Postgresql",
    "tags": [
      "database"
    ],
    "category": "plain"
  },
  "postman": {
    "label": "Postman",
    "tags": [
      "tool",
      "testing"
    ],
    "category": "plain"
  },
  "powershell": {
    "label": "Powershell",
    "tags": [
      "command-line",
      "shell",
      "terminal",
      "cli",
      "windows",
      "cmdlets",
      "ps"
    ],
    "category": "plain"
  },
  "premierepro": {
    "label": "Premierepro",
    "tags": [
      "editor",
      "video",
      "adobepremierepro"
    ],
    "category": "plain"
  },
  "primeng": {
    "label": "Primeng",
    "tags": [
      "angular",
      "ui",
      "component",
      "library",
      "framework"
    ],
    "category": "plain"
  },
  "prisma": {
    "label": "Prisma",
    "tags": [
      "orm",
      "nodejs",
      "typescript"
    ],
    "category": "original"
  },
  "processing": {
    "label": "Processing",
    "tags": [
      "java",
      "python",
      "android",
      "application",
      "ide",
      "framework",
      "processingpy"
    ],
    "category": "plain"
  },
  "processwire": {
    "label": "Processwire",
    "tags": [
      "cms",
      "php",
      "framework"
    ],
    "category": "original"
  },
  "prolog": {
    "label": "Prolog",
    "tags": [
      "programming",
      "logic",
      "language",
      "open-source",
      "swi-prolog"
    ],
    "category": "plain"
  },
  "prometheus": {
    "label": "Prometheus",
    "tags": [
      "monitoring",
      "observability",
      "analysis"
    ],
    "category": "original"
  },
  "protractor": {
    "label": "Protractor",
    "tags": [
      "framework",
      "javascript",
      "protractorjs",
      "protractortest"
    ],
    "category": "plain"
  },
  "proxmox": {
    "label": "Proxmox",
    "tags": [
      "container",
      "lxc",
      "virtual machine"
    ],
    "category": "plain"
  },
  "pug": {
    "label": "Pug",
    "tags": [
      "framework",
      "javascript",
      "nodejs",
      "pugjs"
    ],
    "category": "plain"
  },
  "pulsar": {
    "label": "Pulsar",
    "tags": [
      "open-source",
      "cross-platform",
      "editor",
      "Pulsar Edit"
    ],
    "category": "original"
  },
  "pulumi": {
    "label": "Pulumi",
    "tags": [
      "infrastructure-as-code",
      "cloud"
    ],
    "category": "plain"
  },
  "puppeteer": {
    "label": "Puppeteer",
    "tags": [
      "open-source",
      "devtools protocol",
      "testing",
      "extension"
    ],
    "category": "plain"
  },
  "purescript": {
    "label": "Purescript",
    "tags": [
      "functional",
      "programming",
      "javascript"
    ],
    "category": "original"
  },
  "putty": {
    "label": "Putty",
    "tags": [
      "ssh",
      "server"
    ],
    "category": "plain"
  },
  "pycharm": {
    "label": "Pycharm",
    "tags": [
      "jetbrains",
      "editor"
    ],
    "category": "plain"
  },
  "pydantic": {
    "label": "Pydantic",
    "tags": [
      "python",
      "validation",
      "brand"
    ],
    "category": "tools"
  },
  "pypi": {
    "label": "Pypi",
    "tags": [
      "python",
      "package",
      "programming",
      "Python Package Index"
    ],
    "category": "plain"
  },
  "pyscript": {
    "label": "Pyscript",
    "tags": [
      "browser",
      "python",
      "html",
      "framework"
    ],
    "category": "original-wordmark"
  },
  "pytest": {
    "label": "Pytest",
    "tags": [
      "python",
      "framework",
      "testing"
    ],
    "category": "plain"
  },
  "python": {
    "label": "Python",
    "tags": [
      "programming",
      "language"
    ],
    "category": "plain"
  },
  "pytorch": {
    "label": "Pytorch",
    "tags": [
      "programming",
      "framework",
      "machine-learning",
      "python"
    ],
    "category": "original"
  },
  "qodana": {
    "label": "Qodana",
    "tags": [
      "jetbrains",
      "code quality",
      "security"
    ],
    "category": "plain"
  },
  "qt": {
    "label": "Qt",
    "tags": [
      "framework"
    ],
    "category": "original"
  },
  "qtest": {
    "label": "Qtest",
    "tags": [
      "testing"
    ],
    "category": "original"
  },
  "quarkus": {
    "label": "Quarkus",
    "tags": [
      "java",
      "framework"
    ],
    "category": "plain"
  },
  "quasar": {
    "label": "Quasar",
    "tags": [
      "framework",
      "javascript"
    ],
    "category": "plain"
  },
  "qwik": {
    "label": "Qwik",
    "tags": [
      "framework",
      "open-source"
    ],
    "category": "plain"
  },
  "r": {
    "label": "R",
    "tags": [
      "programming",
      "language",
      "rlang"
    ],
    "category": "plain"
  },
  "rabbitmq": {
    "label": "Rabbitmq",
    "tags": [
      "message-broker",
      "open-source"
    ],
    "category": "original"
  },
  "racket": {
    "label": "Racket",
    "tags": [
      "programming",
      "language"
    ],
    "category": "plain"
  },
  "radstudio": {
    "label": "Radstudio",
    "tags": [
      "editor",
      "IDE",
      "RAD Studio"
    ],
    "category": "plain"
  },
  "rails": {
    "label": "Rails",
    "tags": [
      "framework",
      "rubyonrails"
    ],
    "category": "plain"
  },
  "railway": {
    "label": "Railway",
    "tags": [
      "hosting",
      "platform",
      "deployment"
    ],
    "category": "original"
  },
  "rancher": {
    "label": "Rancher",
    "tags": [
      "kubernetes",
      "orchestrator"
    ],
    "category": "original"
  },
  "raspberrypi": {
    "label": "Raspberrypi",
    "tags": [
      "arm",
      "computer",
      "rpi"
    ],
    "category": "plain"
  },
  "reach": {
    "label": "Reach",
    "tags": [
      "web3",
      "blockchain",
      "development",
      "Reach Lang"
    ],
    "category": "plain"
  },
  "react": {
    "label": "React",
    "tags": [
      "framework",
      "reactjs"
    ],
    "category": "original"
  },
  "reactbootstrap": {
    "label": "Reactbootstrap",
    "tags": [
      "framework",
      "library",
      "frontend",
      "reactjs",
      "javascript",
      "React-Bootstrap",
      "react bootstrap"
    ],
    "category": "original"
  },
  "reactnative": {
    "label": "Reactnative",
    "tags": [
      "framework",
      "react-native"
    ],
    "category": "original"
  },
  "reactnavigation": {
    "label": "Reactnavigation",
    "tags": [
      "routing",
      "navigation",
      "react native",
      "app",
      "open-source"
    ],
    "category": "original"
  },
  "reactrouter": {
    "label": "Reactrouter",
    "tags": [
      "framework",
      "react"
    ],
    "category": "plain"
  },
  "readthedocs": {
    "label": "Readthedocs",
    "tags": [
      "documentation",
      "python",
      "open-source",
      "Read The Docs"
    ],
    "category": "original"
  },
  "realm": {
    "label": "Realm",
    "tags": [
      "sql",
      "database",
      "cloud"
    ],
    "category": "plain"
  },
  "rect": {
    "label": "Rect",
    "tags": [
      "programming",
      "language",
      "rectlang"
    ],
    "category": "plain"
  },
  "reddit": {
    "label": "Reddit",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "redhat": {
    "label": "Redhat",
    "tags": [
      "server",
      "linux"
    ],
    "category": "plain"
  },
  "redis": {
    "label": "Redis",
    "tags": [
      "server",
      "remotedictionaryserver"
    ],
    "category": "plain"
  },
  "redux": {
    "label": "Redux",
    "tags": [
      "framework",
      "reduxjs"
    ],
    "category": "original"
  },
  "reflex": {
    "label": "Reflex",
    "tags": [
      "framework",
      "python",
      "web"
    ],
    "category": "plain"
  },
  "refresh": {
    "label": "Refresh",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "remix": {
    "label": "Remix",
    "tags": [
      "framework",
      "fullstack",
      "web",
      "remix.run"
    ],
    "category": "original"
  },
  "remove": {
    "label": "Remove",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "renpy": {
    "label": "Renpy",
    "tags": [
      "programming",
      "game-engine",
      "engine",
      "python",
      "Ren'Py"
    ],
    "category": "plain"
  },
  "replit": {
    "label": "Replit",
    "tags": [
      "software"
    ],
    "category": "original"
  },
  "rexx": {
    "label": "Rexx",
    "tags": [
      "language"
    ],
    "category": "plain"
  },
  "rider": {
    "label": "Rider",
    "tags": [
      "jetbrains",
      "ide",
      "editor",
      "dotnet"
    ],
    "category": "plain"
  },
  "rocksdb": {
    "label": "Rocksdb",
    "tags": [
      "database"
    ],
    "category": "plain"
  },
  "rockylinux": {
    "label": "Rockylinux",
    "tags": [
      "os",
      "open-source",
      "linux",
      "rocky"
    ],
    "category": "original"
  },
  "rollup": {
    "label": "Rollup",
    "tags": [
      "bundler",
      "build",
      "javascript",
      "rollupjs",
      "rollup.js"
    ],
    "category": "plain"
  },
  "ros": {
    "label": "Ros",
    "tags": [
      "robotics",
      "robotoperatingsystem"
    ],
    "category": "original"
  },
  "rspec": {
    "label": "Rspec",
    "tags": [
      "ruby",
      "framework",
      "testing"
    ],
    "category": "plain"
  },
  "rstudio": {
    "label": "Rstudio",
    "tags": [
      "editor",
      "package",
      "statistics"
    ],
    "category": "plain"
  },
  "ruby": {
    "label": "Ruby",
    "tags": [
      "programming",
      "language",
      "rubylang"
    ],
    "category": "plain"
  },
  "rubymine": {
    "label": "Rubymine",
    "tags": [
      "jetbrains",
      "editor"
    ],
    "category": "plain"
  },
  "rust": {
    "label": "Rust",
    "tags": [
      "programming",
      "language",
      "rustlang"
    ],
    "category": "original"
  },
  "rxjs": {
    "label": "Rxjs",
    "tags": [
      "javascript",
      "library",
      "observability",
      "Reactive Extensions for JavaScript"
    ],
    "category": "plain"
  },
  "safari": {
    "label": "Safari",
    "tags": [
      "browser",
      "applesafari"
    ],
    "category": "plain"
  },
  "salesforce": {
    "label": "Salesforce",
    "tags": [
      "platform",
      "ecommerce"
    ],
    "category": "plain"
  },
  "sanity": {
    "label": "Sanity",
    "tags": [
      "CMS"
    ],
    "category": "plain"
  },
  "sass": {
    "label": "Sass",
    "tags": [
      "pre-processor",
      "css",
      "scss"
    ],
    "category": "original"
  },
  "scala": {
    "label": "Scala",
    "tags": [
      "programming",
      "language",
      "jvm",
      "scalalang"
    ],
    "category": "plain"
  },
  "scalingo": {
    "label": "Scalingo",
    "tags": [
      "cloud",
      "platform",
      "hosting"
    ],
    "category": "plain"
  },
  "scikitlearn": {
    "label": "Scikitlearn",
    "tags": [
      "machine-learning",
      "python",
      "tool",
      "library",
      "scikit-learn",
      "scikit",
      "sklearn"
    ],
    "category": "plain"
  },
  "sdl": {
    "label": "Sdl",
    "tags": [
      "library",
      "cross-platform",
      "multimedia",
      "game",
      "simpledirectmedialayer"
    ],
    "category": "plain"
  },
  "search": {
    "label": "Search",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "selenium": {
    "label": "Selenium",
    "tags": [
      "webdrive",
      "automation"
    ],
    "category": "original"
  },
  "sema": {
    "label": "Sema",
    "tags": [
      "software",
      "development",
      "company",
      "code-review",
      "open-source",
      "Sema Software"
    ],
    "category": "original"
  },
  "sentry": {
    "label": "Sentry",
    "tags": [
      "monitoring",
      "analytics",
      "metrics"
    ],
    "category": "original"
  },
  "sequelize": {
    "label": "Sequelize",
    "tags": [
      "database",
      "language",
      "sequelizejs"
    ],
    "category": "plain"
  },
  "shopware": {
    "label": "Shopware",
    "tags": [
      "cloud",
      "platform"
    ],
    "category": "original"
  },
  "shotgrid": {
    "label": "Shotgrid",
    "tags": [
      "web-application",
      "autodesk",
      "project-management",
      "pipeline",
      "production-tool",
      "production-tracking"
    ],
    "category": "plain"
  },
  "sketch": {
    "label": "Sketch",
    "tags": [
      "application"
    ],
    "category": "plain"
  },
  "slack": {
    "label": "Slack",
    "tags": [
      "chat"
    ],
    "category": "plain"
  },
  "sms": {
    "label": "SMS",
    "tags": [
      "communication",
      "message",
      "contact"
    ],
    "category": "material"
  },
  "snapchat": {
    "label": "Snapchat",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "socketio": {
    "label": "Socketio",
    "tags": [
      "library",
      "networking",
      "websockets"
    ],
    "category": "original"
  },
  "solidity": {
    "label": "Solidity",
    "tags": [
      "programming",
      "language",
      "blockchain",
      "soliditylang"
    ],
    "category": "plain"
  },
  "solidjs": {
    "label": "Solidjs",
    "tags": [
      "javascript",
      "framework",
      "frontend"
    ],
    "category": "plain"
  },
  "sonarqube": {
    "label": "Sonarqube",
    "tags": [
      "tool",
      "security",
      "sonar"
    ],
    "category": "original"
  },
  "sourceengine": {
    "label": "Sourceengine",
    "tags": [
      "game-engine",
      "valve",
      "javascript",
      "source engine"
    ],
    "category": "plain"
  },
  "sourcetree": {
    "label": "Sourcetree",
    "tags": [
      "version-control"
    ],
    "category": "original"
  },
  "spack": {
    "label": "Spack",
    "tags": [
      "package-manager",
      "package",
      "manager",
      "python",
      "open-source"
    ],
    "category": "plain"
  },
  "spicedb": {
    "label": "Spicedb",
    "tags": [
      "database",
      "authorization",
      "access-control",
      "Zanzibar"
    ],
    "category": "plain"
  },
  "splunk": {
    "label": "Splunk",
    "tags": [
      "platform",
      "data",
      "log",
      "monitoring"
    ],
    "category": "original-wordmark"
  },
  "spring": {
    "label": "Spring",
    "tags": [
      "framework",
      "springframework"
    ],
    "category": "original"
  },
  "spss": {
    "label": "Spss",
    "tags": [
      "package",
      "statistics",
      "ibmspss"
    ],
    "category": "plain"
  },
  "spyder": {
    "label": "Spyder",
    "tags": [
      "python",
      "ide",
      "editor",
      "data-science"
    ],
    "category": "plain"
  },
  "sql": {
    "label": "SQL",
    "tags": [
      "database",
      "sql",
      "data",
      "storage"
    ],
    "category": "material"
  },
  "sqlalchemy": {
    "label": "Sqlalchemy",
    "tags": [
      "python",
      "orm"
    ],
    "category": "plain"
  },
  "sqldeveloper": {
    "label": "Sqldeveloper",
    "tags": [
      "tool",
      "database"
    ],
    "category": "plain"
  },
  "sqlite": {
    "label": "Sqlite",
    "tags": [
      "sql",
      "database",
      "db"
    ],
    "category": "plain"
  },
  "ssh": {
    "label": "Ssh",
    "tags": [
      "security",
      "secureshell"
    ],
    "category": "original"
  },
  "stackblitz": {
    "label": "Stackblitz",
    "tags": [
      "IDE",
      "editor",
      "remote-development"
    ],
    "category": "original"
  },
  "stackoverflow": {
    "label": "Stackoverflow",
    "tags": [
      "website",
      "development",
      "community",
      "Stack Overflow"
    ],
    "category": "plain"
  },
  "stata": {
    "label": "Stata",
    "tags": [
      "analysis",
      "data",
      "data-science",
      "software",
      "statistics"
    ],
    "category": "original-wordmark"
  },
  "stenciljs": {
    "label": "Stenciljs",
    "tags": [
      "framework",
      "ui",
      "stencil"
    ],
    "category": "plain"
  },
  "storybook": {
    "label": "Storybook",
    "tags": [
      "framework",
      "documentation",
      "ui",
      "storybookjs"
    ],
    "category": "plain"
  },
  "streamlit": {
    "label": "Streamlit",
    "tags": [
      "python",
      "machine-learning",
      "data-science"
    ],
    "category": "plain"
  },
  "styledcomponents": {
    "label": "Styledcomponents",
    "tags": [
      "css",
      "javascript",
      "js",
      "library",
      "nodejs",
      "web",
      "Styled Components",
      "styled-components"
    ],
    "category": "plain"
  },
  "stylus": {
    "label": "Stylus",
    "tags": [
      "css",
      "pre-processor",
      "styluslang"
    ],
    "category": "original"
  },
  "subversion": {
    "label": "Subversion",
    "tags": [
      "svn",
      "version",
      "apachesubversion"
    ],
    "category": "original"
  },
  "sulu": {
    "label": "Sulu",
    "tags": [
      "cms",
      "platform"
    ],
    "category": "original"
  },
  "supabase": {
    "label": "Supabase",
    "tags": [
      "authentication",
      "cloud-computing-platform",
      "database",
      "storage"
    ],
    "category": "plain"
  },
  "surrealdb": {
    "label": "Surrealdb",
    "tags": [
      "db",
      "database",
      "storage"
    ],
    "category": "plain"
  },
  "svelte": {
    "label": "Svelte",
    "tags": [
      "javascript",
      "framework",
      "compiler",
      "sveltejs"
    ],
    "category": "plain"
  },
  "svgo": {
    "label": "Svgo",
    "tags": [
      "svg",
      "optimization",
      "tool",
      "javascript",
      "library",
      "node.js"
    ],
    "category": "plain"
  },
  "swagger": {
    "label": "Swagger",
    "tags": [
      "development",
      "software",
      "tool",
      "Swagger"
    ],
    "category": "plain"
  },
  "swift": {
    "label": "Swift",
    "tags": [
      "language"
    ],
    "category": "plain"
  },
  "swiper": {
    "label": "Swiper",
    "tags": [
      "library",
      "javascript",
      "open-source"
    ],
    "category": "original"
  },
  "symfony": {
    "label": "Symfony",
    "tags": [
      "framework",
      "php"
    ],
    "category": "original"
  },
  "tailwindcss": {
    "label": "Tailwindcss",
    "tags": [
      "css",
      "framework"
    ],
    "category": "original"
  },
  "talos": {
    "label": "Talos",
    "tags": [
      "container",
      "linux",
      "distribution"
    ],
    "category": "plain"
  },
  "tauri": {
    "label": "Tauri",
    "tags": [
      "nodejs",
      "rust",
      "desktop",
      "framework",
      "programming"
    ],
    "category": "plain"
  },
  "telegram": {
    "label": "Telegram",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "teleport": {
    "label": "Teleport",
    "tags": [
      "ssh",
      "security",
      "auth",
      "authentication",
      "infrastructure"
    ],
    "category": "original"
  },
  "tensorflow": {
    "label": "Tensorflow",
    "tags": [
      "library",
      "machine-learning",
      "deep-learning"
    ],
    "category": "original"
  },
  "terraform": {
    "label": "Terraform",
    "tags": [
      "deployment",
      "architecture",
      "automation"
    ],
    "category": "plain"
  },
  "terramate": {
    "label": "Terramate",
    "tags": [
      "deployment",
      "devops",
      "automation"
    ],
    "category": "original"
  },
  "tex": {
    "label": "Tex",
    "tags": [
      "typesetting-system",
      "markup",
      "tex"
    ],
    "category": "original"
  },
  "thealgorithms": {
    "label": "Thealgorithms",
    "tags": [
      "organization",
      "algorithms"
    ],
    "category": "plain"
  },
  "threedsmax": {
    "label": "Threedsmax",
    "tags": [
      "3d",
      "programming",
      "vfx",
      "graphic",
      "graphics",
      "game",
      "animation",
      "Autodesk 3ds Max",
      "3dsmax"
    ],
    "category": "plain"
  },
  "threejs": {
    "label": "Threejs",
    "tags": [
      "javascript",
      "framework"
    ],
    "category": "original"
  },
  "thymeleaf": {
    "label": "Thymeleaf",
    "tags": [
      "engine",
      "html",
      "java",
      "server"
    ],
    "category": "plain"
  },
  "tiktok": {
    "label": "TikTok",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "titaniumsdk": {
    "label": "Titaniumsdk",
    "tags": [
      "app",
      "mobile",
      "javascript",
      "cross-platform",
      "sdk"
    ],
    "category": "original"
  },
  "tmux": {
    "label": "Tmux",
    "tags": [
      "cli",
      "terminal",
      "multiplexer"
    ],
    "category": "plain"
  },
  "tomcat": {
    "label": "Tomcat",
    "tags": [
      "server"
    ],
    "category": "original"
  },
  "tortoisegit": {
    "label": "Tortoisegit",
    "tags": [
      "git"
    ],
    "category": "plain"
  },
  "towergit": {
    "label": "Towergit",
    "tags": [
      "git",
      "towergitclient"
    ],
    "category": "plain"
  },
  "traefikmesh": {
    "label": "Traefikmesh",
    "tags": [
      "mesh",
      "kubernetes"
    ],
    "category": "original"
  },
  "traefikproxy": {
    "label": "Traefikproxy",
    "tags": [
      "proxy",
      "router"
    ],
    "category": "original"
  },
  "translate": {
    "label": "Translate",
    "tags": [
      "language",
      "i18n",
      "locale",
      "globe",
      "utility"
    ],
    "category": "material"
  },
  "travis": {
    "label": "Travis",
    "tags": [
      "platform",
      "integration",
      "travisci"
    ],
    "category": "plain"
  },
  "trello": {
    "label": "Trello",
    "tags": [
      "platform",
      "organize",
      "atlassiantrello"
    ],
    "category": "plain"
  },
  "trpc": {
    "label": "Trpc",
    "tags": [
      "typescript",
      "javascript",
      "typesafe",
      "api",
      "Typescript Remote Procedure Call"
    ],
    "category": "plain"
  },
  "turbo": {
    "label": "Turbo",
    "tags": [
      "spa",
      "js"
    ],
    "category": "original"
  },
  "twilio": {
    "label": "Twilio",
    "tags": [
      "api",
      "automation",
      "platform"
    ],
    "category": "original"
  },
  "twitch": {
    "label": "Twitch",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "twitter": {
    "label": "Twitter",
    "tags": [
      "auth",
      "x"
    ],
    "category": "original"
  },
  "typescript": {
    "label": "Typescript",
    "tags": [
      "programming",
      "transpiler",
      "javascript",
      "language",
      "ts"
    ],
    "category": "plain"
  },
  "typo3": {
    "label": "Typo3",
    "tags": [
      "cms",
      "php"
    ],
    "category": "original"
  },
  "ubuntu": {
    "label": "Ubuntu",
    "tags": [
      "os",
      "open-source",
      "linux"
    ],
    "category": "plain"
  },
  "unifiedmodelinglanguage": {
    "label": "Unifiedmodelinglanguage",
    "tags": [
      "modeling",
      "design",
      "language",
      "uml",
      "unified modeling language"
    ],
    "category": "plain"
  },
  "unity": {
    "label": "Unity",
    "tags": [
      "C#",
      "c-sharp",
      "csharp",
      "engine",
      "game-engine"
    ],
    "category": "plain"
  },
  "unix": {
    "label": "Unix",
    "tags": [
      "os"
    ],
    "category": "original"
  },
  "unrealengine": {
    "label": "Unrealengine",
    "tags": [
      "c++",
      "engine",
      "game-engine"
    ],
    "category": "original"
  },
  "upload": {
    "label": "Upload",
    "tags": [
      "navigation",
      "utility"
    ],
    "category": "material"
  },
  "uwsgi": {
    "label": "Uwsgi",
    "tags": [
      "hosting",
      "uwebservergatewayinterface"
    ],
    "category": "plain"
  },
  "v8": {
    "label": "V8",
    "tags": [
      "javascript-runtime",
      "framework",
      "javascript",
      "web",
      "cpp",
      "v8 engine"
    ],
    "category": "plain"
  },
  "vaadin": {
    "label": "Vaadin",
    "tags": [
      "framework",
      "java",
      "web"
    ],
    "category": "original"
  },
  "vagrant": {
    "label": "Vagrant",
    "tags": [
      "platform"
    ],
    "category": "plain"
  },
  "vala": {
    "label": "Vala",
    "tags": [
      "programming",
      "language"
    ],
    "category": "plain"
  },
  "vault": {
    "label": "Vault",
    "tags": [
      "tool",
      "security",
      "infrastructure",
      "HashiCorp Vault"
    ],
    "category": "original"
  },
  "veevalidate": {
    "label": "Veevalidate",
    "tags": [
      "vuejs",
      "vuejs-library",
      "package"
    ],
    "category": "original"
  },
  "vercel": {
    "label": "Vercel",
    "tags": [
      "hosting",
      "platform",
      "deployment",
      "git"
    ],
    "category": "original"
  },
  "verdict-check": {
    "label": "Verdict Check",
    "tags": [
      "check",
      "checkmark",
      "yes",
      "verdict",
      "tick",
      "comparison"
    ],
    "category": "original"
  },
  "verdict-cross": {
    "label": "Verdict Cross",
    "tags": [
      "cross",
      "close",
      "no",
      "verdict",
      "x",
      "comparison"
    ],
    "category": "original"
  },
  "vertx": {
    "label": "Vertx",
    "tags": [
      "sdk",
      "java",
      "framework",
      "eclipsevertx"
    ],
    "category": "plain"
  },
  "video_call": {
    "label": "Video Call",
    "tags": [
      "communication",
      "video",
      "contact"
    ],
    "category": "material"
  },
  "vim": {
    "label": "Vim",
    "tags": [
      "editor",
      "viimproved"
    ],
    "category": "plain"
  },
  "visualbasic": {
    "label": "Visualbasic",
    "tags": [
      "programming",
      "language",
      "vb"
    ],
    "category": "plain"
  },
  "visualstudio": {
    "label": "Visualstudio",
    "tags": [
      "editor",
      "vs"
    ],
    "category": "plain"
  },
  "vite": {
    "label": "Vite",
    "tags": [
      "web3",
      "blockchain",
      "DAG"
    ],
    "category": "original"
  },
  "vitejs": {
    "label": "Vitejs",
    "tags": [
      "javascript",
      "build",
      "compiler",
      "esbuild",
      "vite.js",
      "Vite"
    ],
    "category": "plain"
  },
  "vitess": {
    "label": "Vitess",
    "tags": [
      "sharding",
      "database",
      "mysql"
    ],
    "category": "plain"
  },
  "vitest": {
    "label": "Vitest",
    "tags": [
      "framework",
      "open-source",
      "testing",
      "vite"
    ],
    "category": "plain"
  },
  "vscode": {
    "label": "Vscode",
    "tags": [
      "editor",
      "ide",
      "visualstudiocode"
    ],
    "category": "plain"
  },
  "vscodium": {
    "label": "Vscodium",
    "tags": [
      "editor",
      "ide",
      "open-source"
    ],
    "category": "plain"
  },
  "vsphere": {
    "label": "Vsphere",
    "tags": [
      "hypervisor",
      "operating-system",
      "vmware",
      "vmwarevsphere"
    ],
    "category": "plain"
  },
  "vuejs": {
    "label": "Vuejs",
    "tags": [
      "framework"
    ],
    "category": "plain"
  },
  "vuestorefront": {
    "label": "Vuestorefront",
    "tags": [
      "framework"
    ],
    "category": "plain"
  },
  "vuetify": {
    "label": "Vuetify",
    "tags": [
      "css",
      "framework",
      "vuejs-library",
      "material-design"
    ],
    "category": "plain"
  },
  "vulkan": {
    "label": "Vulkan",
    "tags": [
      "api",
      "3d",
      "library",
      "graphics",
      "game"
    ],
    "category": "original"
  },
  "vyper": {
    "label": "Vyper",
    "tags": [
      "blockchain",
      "ethereum",
      "language",
      "programming",
      "python",
      "vyperlang"
    ],
    "category": "original"
  },
  "waku": {
    "label": "Waku",
    "tags": [
      "react",
      "javascript",
      "framework",
      "web"
    ],
    "category": "plain"
  },
  "wasm": {
    "label": "Wasm",
    "tags": [
      "binary",
      "programming",
      "virtual machine",
      "web",
      "language",
      "WebAssembly"
    ],
    "category": "original"
  },
  "web3js": {
    "label": "Web3js",
    "tags": [
      "blockchain",
      "ecommerce",
      "web3.js"
    ],
    "category": "plain"
  },
  "webflow": {
    "label": "Webflow",
    "tags": [
      "cms",
      "ecommerce"
    ],
    "category": "original"
  },
  "webgpu": {
    "label": "Webgpu",
    "tags": [
      "graphics",
      "framework",
      "web"
    ],
    "category": "plain"
  },
  "weblate": {
    "label": "Weblate",
    "tags": [
      "localization"
    ],
    "category": "plain"
  },
  "webpack": {
    "label": "Webpack",
    "tags": [
      "package",
      "manager",
      "webpackjs"
    ],
    "category": "plain"
  },
  "webstorm": {
    "label": "Webstorm",
    "tags": [
      "jetbrains",
      "editor"
    ],
    "category": "plain"
  },
  "whatsapp": {
    "label": "WhatsApp",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "windows11": {
    "label": "Windows11",
    "tags": [
      "os"
    ],
    "category": "original"
  },
  "windows8": {
    "label": "Windows8",
    "tags": [
      "os"
    ],
    "category": "original"
  },
  "wolfram": {
    "label": "Wolfram",
    "tags": [
      "data-science",
      "functional",
      "programming",
      "wolframlanguage"
    ],
    "category": "plain"
  },
  "woocommerce": {
    "label": "Woocommerce",
    "tags": [
      "ecommerce"
    ],
    "category": "plain"
  },
  "wordpress": {
    "label": "Wordpress",
    "tags": [
      "cms"
    ],
    "category": "plain"
  },
  "xamarin": {
    "label": "Xamarin",
    "tags": [
      "application",
      "programming",
      "editor",
      "ide",
      "ios",
      "mobile",
      "apple",
      "android",
      "windows"
    ],
    "category": "original"
  },
  "xcode": {
    "label": "Xcode",
    "tags": [
      "application",
      "editor",
      "ide",
      "ios",
      "iphone",
      "mobile",
      "apple"
    ],
    "category": "plain"
  },
  "xd": {
    "label": "Xd",
    "tags": [
      "design",
      "editor",
      "ui",
      "adobexd"
    ],
    "category": "plain"
  },
  "xml": {
    "label": "Xml",
    "tags": [
      "markup",
      "language",
      "extensiblemarkuplanguage"
    ],
    "category": "plain"
  },
  "yaml": {
    "label": "Yaml",
    "tags": [
      "data",
      "language",
      "YAML Ain't Markup Language"
    ],
    "category": "plain"
  },
  "yarn": {
    "label": "Yarn",
    "tags": [
      "package",
      "manager",
      "javascript",
      "js"
    ],
    "category": "original"
  },
  "yii": {
    "label": "Yii",
    "tags": [
      "php",
      "framework",
      "yesitis"
    ],
    "category": "plain"
  },
  "youtube": {
    "label": "YouTube",
    "tags": [
      "social",
      "brand"
    ],
    "category": "social"
  },
  "yugabytedb": {
    "label": "Yugabytedb",
    "tags": [
      "database",
      "relational",
      "sql",
      "scale",
      "open-source"
    ],
    "category": "plain"
  },
  "yunohost": {
    "label": "Yunohost",
    "tags": [
      "os"
    ],
    "category": "plain"
  },
  "zend": {
    "label": "Zend",
    "tags": [
      "php",
      "framework"
    ],
    "category": "original"
  },
  "zig": {
    "label": "Zig",
    "tags": [
      "language",
      "ziglang"
    ],
    "category": "original"
  },
  "zsh": {
    "label": "Zsh",
    "tags": [
      "shell",
      "script",
      "scripting",
      "language",
      "command"
    ],
    "category": "plain"
  },
  "zustand": {
    "label": "Zustand",
    "tags": [
      "framework"
    ],
    "category": "plain"
  }
}
